{% set name = "pfsspy" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pfsspy-{{ version }}.tar.gz
  sha256: 73eac79a5fdb0eff42f142af3300f814b4597df5ff220922061d85196a4c3a40

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - astropy >=5.0
    - numpy
    - scikit-image
    - scipy
    - sunpy >=4

test:
  imports:
    - pfsspy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pfsspy.readthedocs.io/en/stable/
  summary: Potential field source surface modelling
  description: |
    Potential Field Source Surface model package for Python. This package is based on original code by Anthony Yeates, which can be found at https://github.com/antyeates1983/pfss. The conda-forge version will install pfsspy and all of its core dependencies, but not the two optional dependencies (numba, streamtracer) that improve code performance.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dstansby
    - jgieseler
